### PR TITLE
Example: Using polygon with agents

### PR DESCRIPTION
**Pull request by silent-cipher**
Fixes https://github.com/gizatechxyz/actions-sdk/issues/33

I have added an `ipynb` notebook in `example/agents/` folder. This follows the same method as that of [Arbitrum](https://github.com/gizatechxyz/actions-sdk/blob/main/examples/agents/using_arbitrum.ipynb).

### CODE REVIEW

**Comment by Gonmeso** [comment]
Hi @silent-cipher 

I've read the tutorial and it looks pretty good!

Once I get some time I will run it with my own RPC node and check that it works as expected.

**Comment by silent-cipher** [comment]
I have went through all the steps and got the results. But, it will be great if you go through this once.

**Comment by silent-cipher** [comment]
@Gonmeso, If you get time please review this?

**Comment by Gonmeso** [comment]
Hi @silent-cipher I will review it by EOD

**Comment by Gonmeso** [comment]
Working as expected! Great job and thanks to the contribution. LGTM

**Review by Gonmeso — APPROVED** [review]

**Pull request merged**
